import { index, type RouteConfig, route } from '@react-router/dev/routes'

export default [
  index('routes/home.tsx'),
  route('login', 'routes/login.tsx'),
  route('register', 'routes/register.tsx'),
  route('logout', 'routes/logout.tsx'),
  route('verify-email', 'routes/verify-email.tsx'),
  route('resend-verification', 'routes/resend-verification.tsx'),
  route('books/:slug', 'routes/book.tsx'),
  route('books/:slug/shelf', 'routes/book-shelf.tsx'),
  route('reviews/:id/helpful', 'routes/review-helpful.tsx'),
  route('reviews/:id/report', 'routes/review-report.tsx'),
  route('authors/:slug', 'routes/author.tsx'),
  route('genres', 'routes/genres.tsx'),
  route('genres/:slug', 'routes/genre.tsx'),
  route('series/:slug', 'routes/series.tsx'),
  route('u/:username', 'routes/profile.tsx'),
  route('u/:username/library', 'routes/library.tsx'),
  route('resolve', 'routes/resolve.tsx'),
  route('search', 'routes/search.tsx'),
  route('search/suggest', 'routes/search-suggest.tsx'),
  route('notifications/read', 'routes/notifications-read.tsx'),
  route('forgot-password', 'routes/forgot-password.tsx'),
  route('reset-password', 'routes/reset-password.tsx'),
  route('confirm-email-change', 'routes/confirm-email-change.tsx'),
  route('settings/avatar', 'routes/settings-avatar.tsx'),
  route('settings/export', 'routes/settings-export.tsx'),
  route('settings', 'routes/settings.tsx', [
    index('routes/settings-index.tsx'),
    route('profile', 'routes/settings-profile.tsx'),
    route('security', 'routes/settings-security.tsx'),
  ]),
  route('admin/audit.csv', 'routes/admin-audit-csv.ts'),
  route('admin', 'routes/admin.tsx', [
    index('routes/admin-index.tsx'),
    route('reviews', 'routes/admin-reviews.tsx'),
    route('reports', 'routes/admin-reports.tsx'),
    route('users', 'routes/admin-users.tsx'),
    route('users/:id', 'routes/admin-user.tsx'),
    route('audit', 'routes/admin-audit.tsx'),
    route('books/:id', 'routes/admin-book.tsx'),
    route('catalog', 'routes/admin-catalog.tsx'),
    route('catalog/merge', 'routes/admin-catalog-merge.tsx'),
    route('catalog/genres', 'routes/admin-catalog-genres.tsx'),
  ]),
] satisfies RouteConfig
