-- Reference data from D-015: the 42 curated Genres and their starter Subject-to-Genre rules (PRD §5.1, §5.4).
-- Admins edit these in the Catalog admin after M7. IDs use Postgres 18's native uuidv7().
INSERT INTO "genres" ("id", "slug", "name", "featured") VALUES
	(uuidv7(), 'literary-fiction', 'Literary Fiction', true),
	(uuidv7(), 'contemporary-fiction', 'Contemporary Fiction', false),
	(uuidv7(), 'historical-fiction', 'Historical Fiction', true),
	(uuidv7(), 'classics', 'Classics', true),
	(uuidv7(), 'science-fiction', 'Science Fiction', true),
	(uuidv7(), 'dystopian', 'Dystopian', false),
	(uuidv7(), 'fantasy', 'Fantasy', true),
	(uuidv7(), 'horror', 'Horror', false),
	(uuidv7(), 'mystery', 'Mystery', true),
	(uuidv7(), 'thriller-suspense', 'Thriller & Suspense', true),
	(uuidv7(), 'crime-fiction', 'Crime Fiction', false),
	(uuidv7(), 'romance', 'Romance', true),
	(uuidv7(), 'adventure', 'Adventure', false),
	(uuidv7(), 'westerns', 'Westerns', false),
	(uuidv7(), 'humor-satire', 'Humor & Satire', false),
	(uuidv7(), 'short-stories', 'Short Stories', false),
	(uuidv7(), 'poetry', 'Poetry', false),
	(uuidv7(), 'drama-plays', 'Drama & Plays', false),
	(uuidv7(), 'graphic-novels-comics', 'Graphic Novels & Comics', false),
	(uuidv7(), 'mythology-folklore', 'Mythology & Folklore', false),
	(uuidv7(), 'young-adult', 'Young Adult', true),
	(uuidv7(), 'middle-grade', 'Middle Grade', false),
	(uuidv7(), 'childrens-books', 'Children''s Books', false),
	(uuidv7(), 'biography', 'Biography', true),
	(uuidv7(), 'memoir', 'Memoir', true),
	(uuidv7(), 'history', 'History', true),
	(uuidv7(), 'true-crime', 'True Crime', false),
	(uuidv7(), 'science-nature', 'Science & Nature', true),
	(uuidv7(), 'technology', 'Technology', false),
	(uuidv7(), 'philosophy', 'Philosophy', false),
	(uuidv7(), 'psychology', 'Psychology', false),
	(uuidv7(), 'religion-spirituality', 'Religion & Spirituality', false),
	(uuidv7(), 'politics-society', 'Politics & Society', false),
	(uuidv7(), 'business-economics', 'Business & Economics', false),
	(uuidv7(), 'self-help', 'Self-Help', false),
	(uuidv7(), 'health-wellness', 'Health & Wellness', false),
	(uuidv7(), 'food-cooking', 'Food & Cooking', false),
	(uuidv7(), 'travel', 'Travel', false),
	(uuidv7(), 'arts-photography', 'Arts & Photography', false),
	(uuidv7(), 'music', 'Music', false),
	(uuidv7(), 'sports-outdoors', 'Sports & Outdoors', false),
	(uuidv7(), 'essays', 'Essays', false);
--> statement-breakpoint
UPDATE "genres" SET "parent_id" = (SELECT "id" FROM "genres" WHERE "slug" = 'science-fiction') WHERE "slug" = 'dystopian';
--> statement-breakpoint
INSERT INTO "subject_genre_rules" ("id", "pattern", "genre_id", "priority")
SELECT uuidv7(), v."pattern", g."id", v."priority"
FROM (VALUES
	('literary fiction', 'literary-fiction', 50),
	('psychological fiction', 'literary-fiction', 50),
	('contemporary fiction', 'contemporary-fiction', 50),
	('domestic fiction', 'contemporary-fiction', 50),
	('historical fiction', 'historical-fiction', 50),
	('classic literature', 'classics', 50),
	('classics', 'classics', 50),
	('science fiction', 'science-fiction', 50),
	('space opera', 'science-fiction', 50),
	('space warfare', 'science-fiction', 50),
	('dystopia', 'dystopian', 50),
	('dystopian', 'dystopian', 50),
	('fantasy fiction', 'fantasy', 50),
	('fantasy', 'fantasy', 50),
	('magic', 'fantasy', 20),
	('horror', 'horror', 50),
	('ghost stories', 'horror', 50),
	('vampires', 'horror', 50),
	('mystery', 'mystery', 50),
	('detective and mystery stories', 'mystery', 50),
	('private investigators', 'mystery', 50),
	('thriller', 'thriller-suspense', 50),
	('suspense', 'thriller-suspense', 50),
	('espionage', 'thriller-suspense', 50),
	('crime fiction', 'crime-fiction', 50),
	('noir', 'crime-fiction', 50),
	('romance', 'romance', 50),
	('love stories', 'romance', 50),
	('adventure stories', 'adventure', 50),
	('adventure fiction', 'adventure', 50),
	('western stories', 'westerns', 50),
	('westerns', 'westerns', 50),
	('humorous fiction', 'humor-satire', 50),
	('humor', 'humor-satire', 20),
	('satire', 'humor-satire', 50),
	('short stories', 'short-stories', 50),
	('poetry', 'poetry', 50),
	('poems', 'poetry', 50),
	('drama', 'drama-plays', 20),
	('plays', 'drama-plays', 20),
	('graphic novels', 'graphic-novels-comics', 50),
	('comic books', 'graphic-novels-comics', 50),
	('comics', 'graphic-novels-comics', 50),
	('mythology', 'mythology-folklore', 50),
	('folklore', 'mythology-folklore', 50),
	('legends', 'mythology-folklore', 50),
	('young adult fiction', 'young-adult', 50),
	('teen', 'young-adult', 20),
	('middle grade', 'middle-grade', 50),
	('juvenile fiction', 'childrens-books', 50),
	('juvenile literature', 'childrens-books', 50),
	('picture books', 'childrens-books', 50),
	('biography', 'biography', 50),
	('autobiography', 'biography', 50),
	('memoir', 'memoir', 50),
	('history', 'history', 10),
	('true crime', 'true-crime', 50),
	('criminal investigation', 'true-crime', 50),
	('popular science', 'science-nature', 50),
	('natural history', 'science-nature', 50),
	('physics', 'science-nature', 50),
	('biology', 'science-nature', 50),
	('astronomy', 'science-nature', 50),
	('technology', 'technology', 50),
	('computer science', 'technology', 50),
	('programming', 'technology', 50),
	('philosophy', 'philosophy', 50),
	('ethics', 'philosophy', 50),
	('psychology', 'psychology', 50),
	('religion', 'religion-spirituality', 50),
	('spirituality', 'religion-spirituality', 50),
	('theology', 'religion-spirituality', 50),
	('political science', 'politics-society', 50),
	('politics', 'politics-society', 20),
	('sociology', 'politics-society', 50),
	('social conditions', 'politics-society', 50),
	('business', 'business-economics', 20),
	('economics', 'business-economics', 50),
	('management', 'business-economics', 50),
	('self-help', 'self-help', 50),
	('self-actualization', 'self-help', 50),
	('success', 'self-help', 20),
	('health', 'health-wellness', 20),
	('nutrition', 'health-wellness', 50),
	('fitness', 'health-wellness', 50),
	('cooking', 'food-cooking', 50),
	('cookbooks', 'food-cooking', 50),
	('food', 'food-cooking', 20),
	('travel', 'travel', 20),
	('description and travel', 'travel', 50),
	('art', 'arts-photography', 20),
	('photography', 'arts-photography', 50),
	('design', 'arts-photography', 20),
	('music', 'music', 20),
	('musicians', 'music', 50),
	('sports', 'sports-outdoors', 20),
	('outdoor recreation', 'sports-outdoors', 50),
	('essays', 'essays', 50)
) AS v("pattern", "slug", "priority")
JOIN "genres" g ON g."slug" = v."slug";
