export const copy = {
  shell: {
    brand: 'RePrint',
    skipToContent: 'Skip to main content',
    homeLinkLabel: 'RePrint home',
    searchLabel: 'Search',
    accountLabel: 'Account',
    legalNavLabel: 'Legal and help',
    openLibraryCredit: 'Book data and covers courtesy of',
    openLibraryName: 'Open Library',
    openLibraryUrl: 'https://openlibrary.org',
    logIn: 'Log in',
    register: 'Register',
    logOut: 'Log out',
    accountMenuLabel: 'Account menu',
    legalLinks: [
      { label: 'About', href: '/about' },
      { label: 'Terms of Service', href: '/terms' },
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Community Guidelines', href: '/community-guidelines' },
      { label: 'Contact', href: '/contact' },
    ],
  },
  home: {
    title: 'Discover books. Read reviews you can trust.',
    lead: 'Every review on RePrint is approved by a moderator before anyone sees it.',
    cta: 'Browse books',
  },
  auth: {
    emailLabel: 'Email',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    inviteCodeLabel: 'Invite code',
    inviteCodeRequired: 'Enter your invite code.',
    inviteCodeHint: 'RePrint is invite-only for now. Enter the code you were given.',
    submitting: 'Please wait…',
    genericError: 'Something went wrong. Please try again.',
    login: {
      title: 'Log in',
      submit: 'Log in',
      noAccount: 'New to RePrint?',
      registerLink: 'Create an account',
      forgotLink: 'Forgot your password?',
    },
    register: {
      title: 'Create your account',
      submit: 'Create account',
      haveAccount: 'Already have an account?',
      loginLink: 'Log in',
      passwordHint: 'At least 12 characters.',
      usernameHint: '3 to 30 letters, numbers, or underscores.',
      checkEmailTitle: 'Check your email',
      checkEmailBody:
        'If the address can be used, we sent a link to confirm it. The link works for 24 hours.',
    },
  },
  error: {
    title: 'Something went wrong',
    notFoundTitle: 'Page not found',
    body: 'We could not load this page. Please try again in a moment.',
    notFoundBody: 'The page you are looking for does not exist.',
    home: 'Back to home',
  },
} as const
