export const copy = {
  shell: {
    brand: 'RePrint',
    skipToContent: 'Skip to main content',
    homeLinkLabel: 'RePrint home',
    searchLabel: 'Search',
    search: {
      inputLabel: 'Search books and authors',
      placeholder: 'Search books and authors',
      submit: 'Search',
      suggestionsLabel: 'Suggestions',
      bookKind: 'Book',
      authorKind: 'Author',
      resultCount: (count: number) =>
        count === 0
          ? 'No suggestions'
          : `${count} ${count === 1 ? 'suggestion' : 'suggestions'} available`,
    },
    accountLabel: 'Account',
    legalNavLabel: 'Legal and help',
    openLibraryCredit: 'Book data and covers courtesy of',
    openLibraryName: 'Open Library',
    openLibraryUrl: 'https://openlibrary.org',
    logIn: 'Log in',
    register: 'Register',
    logOut: 'Log out',
    accountMenuLabel: 'Account menu',
    notifications: {
      label: 'Notifications',
      unreadLabel: (count: number) => `Notifications, ${count} unread`,
      empty: 'No notifications yet.',
      unreadMark: 'Unread',
      messages: {
        review_approved: 'Your review was approved and is now published.',
        review_rejected: 'Your review was not approved.',
        review_unpublished: 'Your review was unpublished.',
        password_changed: 'Your password was changed.',
        email_changed: 'Your email address was changed.',
      },
      readFailed: 'We could not update your notifications.',
    },
    legalLinks: [
      { label: 'About', href: '/about' },
      { label: 'Terms of Service', href: '/terms' },
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Community Guidelines', href: '/community-guidelines' },
      { label: 'Contact', href: '/contact' },
    ],
  },
  seo: {
    defaultDescription:
      'RePrint is a place to discover books and read reviews you can trust. Every review is approved by a moderator.',
  },
  home: {
    title: 'Discover books. Read reviews you can trust.',
    lead: 'Every review on RePrint is approved by a moderator before anyone sees it.',
    metaDescription:
      'Discover books and read reviews you can trust. Every review on RePrint is approved by a moderator.',
    empty: 'Nothing to show here yet. Search for a book to get started.',
    loadFailed: 'Could not load recommendations right now.',
    signInPrompt: 'Sign in to write reviews and mark the ones you find helpful.',
    signIn: 'Sign in',
    register: 'Create an account',
    recentlyReviewed: 'Recently reviewed',
    topRated: 'Top rated on RePrint',
    mostReviewedThisMonth: 'Most reviewed this month',
    browseByGenre: 'Browse by genre',
    allGenres: 'All genres',
    featuredReview: 'Featured review',
    featuredReviewOn: 'Review of',
    readMore: 'Read the full review',
  },
  shelves: {
    label: (title: string) => `Shelf for ${title}`,
    none: 'Add to shelf',
    want_to_read: 'Want to Read',
    reading: 'Reading',
    read: 'Read',
    remove: 'Remove',
    failed: "We couldn't update your shelf. Please try again.",
    signIn: 'Sign in to shelve',
  },
  search: {
    title: (q: string) => (q ? `Search: ${q}` : 'Search'),
    heading: 'Search results',
    prompt: 'Type at least 2 characters to search for books and authors.',
    queryLabel: 'Search books and authors',
    tabsLabel: 'Result types',
    booksTab: 'Books',
    authorsTab: 'Authors',
    filtersLabel: 'Filters',
    language: 'Language',
    decade: 'First published',
    minRating: 'Minimum rating',
    sort: 'Sort by',
    anyOption: 'Any',
    decadeOption: (year: number) => `${year}s`,
    minRatingOption: (stars: number) => `${stars} stars and up`,
    genre: 'Genre',
    catalogOnly: 'Genre, language, and rating filters show only books already on RePrint.',
    sorts: {
      relevance: 'Relevance',
      most_reviewed: 'Most reviewed',
      highest_rated: 'Highest rated',
      newest: 'Newest',
    },
    apply: 'Apply filters',
    clear: 'Clear filters',
    resultCount: (count: number) => `${count} ${count === 1 ? 'result' : 'results'} on this page`,
    empty: 'No results found. Try a different spelling or fewer filters.',
    sourceUnavailable:
      "We couldn't reach our wider book search just now, so these are only books already on RePrint.",
    loadFailed: "We couldn't load search results. Please try again in a moment.",
    pagesLabel: 'Pages',
    previous: 'Previous',
    next: 'Next',
    pageOf: (page: number) => `Page ${page}`,
  },
  resolve: {
    title: 'Opening book',
    failedHeading: 'We couldn’t load this book right now',
    failedBody: 'The book service didn’t respond in time. Try again in a moment.',
    retry: 'Try again',
    loading: 'Loading this book…',
    notFoundHeading: 'We couldn’t find that book',
    notFoundBody: 'This search result has expired. Search again to find it.',
    backToSearch: 'Back to search',
  },
  books: {
    coverAlt: (title: string) => `Cover of ${title}`,
    byAuthors: (names: string) => `by ${names}`,
    firstPublished: (year: number) => `First published ${year}`,
    noReviews: 'No RePrint reviews yet',
    ratingLabel: (average: string, count: number) =>
      `Rated ${average} out of 5 from ${count} ${count === 1 ? 'review' : 'reviews'}`,
    reviewCount: (count: number) => `(${count})`,
    page: {
      roles: {
        author: 'by',
        translator: 'translated by',
        illustrator: 'illustrated by',
        editor: 'edited by',
        narrator: 'narrated by',
        other: 'with',
      },
      seriesPosition: (name: string, position: number) => `${name}, book ${position}`,
      pages: (count: number) => `${count} pages`,
      publisher: (name: string) => `Published by ${name}`,
      genresLabel: 'Genres',
      descriptionHeading: 'About this book',
      noDescription: 'No description yet',
      readMore: 'Read more',
      readLess: 'Read less',
      editionsHeading: (count: number) => `Editions (${count})`,
      formats: {
        hardcover: 'Hardcover',
        paperback: 'Paperback',
        ebook: 'E-book',
        audiobook: 'Audiobook',
        unknown: 'Format unknown',
      },
      isbn: (isbn: string) => `ISBN ${isbn}`,
      moreByHeading: (name: string) => `More by ${name}`,
      metaDescription: (title: string, authors: string) =>
        authors
          ? `${title} by ${authors}: ratings and reviews on RePrint.`
          : `${title}: ratings and reviews on RePrint.`,
      loadFailed: "We couldn't load this book right now. Please try again in a moment.",
    },
  },
  redesign: {
    starRating: (average: string) => `Rated ${average} out of 5`,
    trustBadge: 'Read by a moderator',
    bookRail: {
      scrollLabel: (label: string) => `${label}, scrolls sideways`,
    },
    genreTile: {
      books: (count: number) => `${count} ${count === 1 ? 'book' : 'books'}`,
    },
    reviewExcerpt: {
      by: (name: string) => `by ${name}`,
      readFull: (title: string) => `Read the full review of ${title}`,
      rating: (rating: number) => `${rating} out of 5 stars`,
    },
    sectionNav: {
      label: 'On this page',
    },
    ratingBreakdown: {
      heading: 'Rating breakdown',
      average: (average: string) => `${average} out of 5`,
      count: (count: number) => `${count} ${count === 1 ? 'rating' : 'ratings'}`,
      barLabel: (stars: number, count: number) =>
        `${stars} ${stars === 1 ? 'star' : 'stars'}: ${count} ${count === 1 ? 'review' : 'reviews'}`,
      clearFilter: 'Show all ratings',
    },
    series: {
      heading: 'In this series',
      position: (position: string, total: number | null) =>
        total ? `Book ${position} of ${total}` : `Book ${position}`,
      youAreHere: "You're here",
      upNext: (title: string) => `Up next: ${title}`,
      viewSeries: 'View the series',
    },
    author: {
      heading: 'About the author',
      lifeSpan: (born: string | null, died: string | null) =>
        born && died ? `${born} to ${died}` : born ? `Born ${born}` : (died ?? ''),
      bookCount: (count: number) => `${count} ${count === 1 ? 'book' : 'books'} on RePrint`,
      viewAuthor: (name: string) => `More about ${name}`,
      match: 'Author',
    },
    editions: {
      heading: (count: number) => `Editions (${count})`,
      filterLabel: 'Filter by format',
      allFormats: 'All formats',
      empty: 'No editions in this format.',
      seeAll: 'See all editions',
      published: (year: number) => `Published ${year}`,
    },
  },
  reviews: {
    starRating: {
      groupLabel: 'Your rating',
      starLabel: (n: number) => `${n} ${n === 1 ? 'star' : 'stars'}`,
    },
    spoilers: {
      notice: 'This review contains spoilers.',
      show: 'Show spoilers',
      hide: 'Hide spoilers',
    },
    report: {
      title: 'Report this review',
      intro: 'Tell the moderators what is wrong. Reports are private.',
      reasonLegend: 'Reason',
      reasons: {
        unmarked_spoiler: 'Unmarked spoiler',
        offensive: 'Offensive or hateful',
        spam: 'Spam or advertising',
        off_topic: 'Off-topic',
        other: 'Other',
      },
      noteLabel: 'Note',
      noteHint: (max: number) => `Up to ${max} characters.`,
      noteRequired: 'Tell us what is wrong.',
      submit: 'Send report',
      sending: 'Sending…',
      cancel: 'Cancel',
      close: 'Close',
      received: 'Thank you. The moderators will take a look.',
      failed: "We couldn't send your report. Please try again.",
    },
    list: {
      heading: 'Reviews',
      summaryHeading: 'Rating summary',
      average: (average: string) => `${average} out of 5`,
      count: (count: number) => `${count} ${count === 1 ? 'review' : 'reviews'}`,
      distributionLabel: 'Ratings by star',
      barLabel: (stars: number, count: number, active: boolean) =>
        `${stars} ${stars === 1 ? 'star' : 'stars'}: ${count} ${count === 1 ? 'review' : 'reviews'}${active ? ' (filter on)' : ''}`,
      distributionText: (counts: number[]) =>
        counts.map((n, i) => `${5 - i} stars: ${n}`).join(', '),
      sortLabel: 'Sort by',
      sorts: {
        most_helpful: 'Most helpful',
        newest: 'Newest',
        highest: 'Highest rated',
        lowest: 'Lowest rated',
      },
      filterLabel: 'Show',
      allRatings: 'All ratings',
      starsOnly: (stars: number) => `${stars} ${stars === 1 ? 'star' : 'stars'} only`,
      clearFilter: 'Show all ratings',
      apply: 'Apply',
      empty: 'No reviews yet. Be the first to write one.',
      emptyFiltered: 'No reviews with this rating.',
      by: (name: string) => `by ${name}`,
      ratingOf: (rating: number) => `${rating} out of 5 stars`,
      helpful: (count: number) =>
        `${count} ${count === 1 ? 'person' : 'people'} found this helpful`,
      markHelpful: 'Mark as helpful',
      markedHelpful: 'Marked as helpful',
      helpfulFailed: "We couldn't save your vote. Please try again.",
      report: 'Report',
      pagesLabel: 'Review pages',
      previous: 'Previous',
      next: 'Next',
      pageOf: (page: number, total: number) => `Page ${page} of ${total}`,
      loadFailed: "We couldn't load reviews right now. Please try again in a moment.",
    },
    mine: {
      heading: 'Your review',
      writeHeading: 'Write a review',
      write: 'Write a review',
      edit: 'Edit your review',
      editHeading: 'Edit your review',
      cancel: 'Cancel',
      delete: 'Delete review',
      deleting: 'Deleting…',
      confirmDelete: 'Delete this review permanently? This cannot be undone.',
      confirmDeleteYes: 'Yes, delete it',
      confirmDeleteNo: 'Keep it',
      statuses: {
        pending: 'Pending approval',
        approved: 'Approved',
        rejected: 'Rejected',
        unpublished: 'Unpublished',
      },
      statusNotes: {
        pending: 'A moderator will look at it soon. Only you can see it until then.',
        approved: 'Everyone can see this review.',
        rejected: 'Only you can see this review. You can edit it and send it again.',
        unpublished: 'This review was taken down. Only you can see it.',
      },
      rejectionReason: (reason: string) => `Moderator's reason: ${reason}`,
      editWarning: 'Editing sends your review back for approval, and it is hidden until then.',
      spoilersFlag: 'Contains spoilers',
      verifyPrompt: 'Confirm your email address to write a review.',
      logInPrompt: 'to write a review.',
      logIn: 'Log in',
      saved: 'Thanks. Your review was sent for approval.',
      deleted: 'Your review was deleted.',
      loadFailed: "We couldn't load your review right now.",
    },
    form: {
      ratingLabel: 'Your rating',
      ratingRequired: 'Choose a rating from 1 to 5 stars.',
      headlineLabel: 'Headline (optional)',
      headlineCounter: (used: number, max: number) => `${used} of ${max} characters`,
      bodyLabel: 'Your review',
      bodyHint: 'Plain text. Links are shown as text and are not clickable.',
      bodyCounter: (used: number, min: number, max: number) =>
        used < min
          ? `${used} of ${max} characters (at least ${min} needed)`
          : `${used} of ${max} characters`,
      spoilersLabel: 'This review contains spoilers',
      spoilersHint: 'The text is hidden behind a "Show spoilers" button.',
      editionLabel: 'Edition you read (optional)',
      editionNone: 'Not specified',
      submit: 'Submit for approval',
      resubmit: 'Resubmit for approval',
      submitting: 'Submitting…',
      failed: 'We could not save your review. Please try again.',
    },
  },
  author: {
    photoAlt: (name: string) => `Photo of ${name}`,
    born: (year: string) => `Born ${year}`,
    lifeSpan: (birth: string, death: string) => `${birth} to ${death}`,
    died: (year: string) => `Died ${year}`,
    aboutHeading: 'About the author',
    noBio: 'No biography yet',
    alsoKnownAs: (names: string) => `Also known as ${names}`,
    booksHeading: 'Books',
    noBooks: 'No books on RePrint yet',
    roleHeadings: {
      author: 'Written',
      translator: 'Translated',
      illustrator: 'Illustrated',
      editor: 'Edited',
      narrator: 'Narrated',
      other: 'Other contributions',
    },
    metaDescription: (name: string) => `Books by ${name}, with ratings and reviews on RePrint.`,
    loadFailed: "We couldn't load this author right now. Please try again in a moment.",
  },
  genres: {
    indexTitle: 'Genres',
    indexIntro: 'Browse books by genre.',
    indexEmpty: 'No genres yet',
    indexMetaDescription: 'Browse books by genre, with ratings and reviews on RePrint.',
    parentLabel: 'Parent genre',
    childrenHeading: 'Genres within this one',
    allGenres: 'All genres',
    sortLabel: 'Sort by',
    sorts: {
      top_rated: 'Top rated',
      most_reviewed: 'Most reviewed',
      newest_review: 'Newest review',
    },
    noBooks: 'No books in this genre yet',
    pagesLabel: 'Pages',
    previous: 'Previous',
    next: 'Next',
    pageOf: (page: number) => `Page ${page}`,
    metaDescription: (name: string) => `Books in ${name}, with ratings and reviews on RePrint.`,
    loadFailed: "We couldn't load genres right now. Please try again in a moment.",
  },
  series: {
    booksHeading: 'Books in reading order',
    position: (position: number) => `Book ${position}`,
    noPosition: 'Not numbered',
    noBooks: 'No books in this series yet',
    metaDescription: (name: string) => `${name}: books in reading order, with ratings on RePrint.`,
    loadFailed: "We couldn't load this series right now. Please try again in a moment.",
  },
  profile: {
    title: (name: string) => `${name} | Profile`,
    metaDescription: (name: string, reviews: number) =>
      `${name} on RePrint: ${reviews} approved ${reviews === 1 ? 'review' : 'reviews'}.`,
    avatarAlt: (name: string) => `${name}'s avatar`,
    handle: (username: string) => `@${username}`,
    joined: (date: string) => `Joined ${date}`,
    totalsLabel: 'Totals',
    reviewsTotal: (count: number) => `${count} ${count === 1 ? 'review' : 'reviews'}`,
    helpfulTotal: (count: number) => `${count} helpful ${count === 1 ? 'vote' : 'votes'}`,
    tabsLabel: 'Profile sections',
    reviewsTab: 'Reviews',
    libraryTab: 'Library',
    noReviews: 'No approved reviews yet.',
    ratingOf: (rating: number) => `${rating} out of 5 stars`,
    pagesLabel: 'Pages',
    previous: 'Previous',
    next: 'Next',
    pageOf: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
    loadFailed: "We couldn't load this profile right now. Please try again in a moment.",
  },
  library: {
    title: (name: string) => `${name}'s library`,
    heading: (username: string) => `${username}'s library`,
    ownHeading: 'Your library',
    metaDescription: (username: string) => `Books ${username} has shelved on RePrint.`,
    tabsLabel: 'Shelves',
    tabs: { all: 'All', reading: 'Reading', want_to_read: 'Want to Read', read: 'Read' },
    tabLabel: (name: string, count: number) => `${name} (${count})`,
    sortLabel: 'Sort by',
    sorts: {
      added_desc: 'Newest added',
      added_asc: 'Oldest added',
      title: 'Title (A to Z)',
      author: 'Author',
    },
    apply: 'Apply',
    empty: 'Nothing on this shelf yet.',
    discoverPrompt: 'Find something to read',
    privateHeading: 'This library is private',
    privateBody: "This library is private, or it doesn't exist.",
    pagesLabel: 'Pages',
    previous: 'Previous',
    next: 'Next',
    pageOf: (page: number, totalPages: number) => `Page ${page} of ${totalPages}`,
    loadFailed: "We couldn't load this library right now. Please try again in a moment.",
  },
  auth: {
    emailLabel: 'Email',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    inviteCodeLabel: 'Invite code',
    inviteCodeRequired: 'Enter your invite code.',
    inviteCodeHint: 'RePrint is invite-only for now. Enter the code you were given.',
    submitting: 'Please wait…',
    genericError: 'Something went wrong. Please try again.',
    login: {
      title: 'Log in',
      submit: 'Log in',
      noAccount: 'New to RePrint?',
      registerLink: 'Create an account',
      forgotLink: 'Forgot your password?',
    },
    register: {
      title: 'Create your account',
      submit: 'Create account',
      haveAccount: 'Already have an account?',
      loginLink: 'Log in',
      passwordHint: 'At least 12 characters.',
      usernameHint: '3 to 30 letters, numbers, or underscores.',
      checkEmailTitle: 'Check your email',
      checkEmailBody:
        'If the address can be used, we sent a link to confirm it. The link works for 24 hours.',
    },
    forgot: {
      title: 'Reset your password',
      lead: 'Enter your email and we will send a link to choose a new password.',
      submit: 'Send reset link',
      backToLogin: 'Back to log in',
      checkEmailTitle: 'Check your email',
      checkEmailBody:
        'If that address has an account, we sent a link to reset the password. The link works for 1 hour.',
    },
    reset: {
      title: 'Choose a new password',
      submit: 'Set new password',
      newPasswordLabel: 'New password',
      passwordHint: 'At least 12 characters.',
      doneTitle: 'Password updated',
      doneBody: 'Your password has been changed. Log in with it to continue.',
      logIn: 'Log in',
      invalidTitle: 'This link cannot be used',
      invalidBody: 'The reset link is missing, has expired, or was already used.',
      requestNew: 'Request a new link',
    },
    verify: {
      successTitle: 'Email confirmed',
      successBody: 'Thanks. Your email address is verified, so you can now write reviews.',
      failedTitle: 'This link cannot be used',
      failedBody: 'The verification link is missing, has expired, or was already used.',
      failedHelp: 'Log in and use the banner at the top of any page to send a new link.',
      continue: 'Continue to RePrint',
      logIn: 'Log in',
    },
    banner: {
      label: 'Email verification',
      message: 'Confirm your email address to write reviews, vote, and report.',
      resend: 'Resend link',
      sending: 'Sending…',
      sent: 'We sent a new link. It works for 24 hours.',
      failed: 'We could not send the link. Please try again.',
    },
  },
  settings: {
    title: 'Settings',
    navLabel: 'Settings sections',
    profileTab: 'Profile',
    securityTab: 'Security',
    profile: {
      title: 'Profile',
      lead: 'This is what other Members see on your profile.',
      displayNameLabel: 'Display name',
      bioLabel: 'Bio',
      bioCounter: (used: number, max: number) => `${used} of ${max} characters`,
      libraryPublicLabel: 'Show my library on my profile',
      libraryPublicHint: 'When this is off, only you can see which Books are on your Shelves.',
      emailDecisionsLabel: 'Email me when a moderator decides on my review',
      emailDecisionsHint: 'Security emails about your account are always sent.',
      save: 'Save changes',
      saving: 'Saving…',
      saved: 'Your profile was saved.',
      failed: 'We could not save your profile. Please try again.',
    },
    avatar: {
      title: 'Avatar',
      currentAlt: 'Your current avatar',
      previewAlt: 'Preview of your new avatar',
      fileLabel: 'Choose an image',
      fileHint: 'JPEG, PNG, WebP, or GIF up to 5 MB. It is cropped to a square.',
      upload: 'Upload avatar',
      uploading: 'Uploading…',
      uploaded: 'Your avatar was updated.',
      chooseFile: 'Choose an image to upload.',
      failed: 'We could not upload the image. Please try again.',
    },
    security: {
      title: 'Security',
      currentPasswordLabel: 'Current password',
      email: {
        title: 'Email address',
        lead: (email: string) =>
          `Your email is ${email}. A new address takes effect once you confirm it.`,
        newEmailLabel: 'New email address',
        submit: 'Change email',
        submitting: 'Sending…',
        pendingTitle: 'Check your new inbox',
        pendingBody: (email: string) =>
          `We sent a link to ${email}. Your email stays the same until you open it. The link works for 24 hours.`,
        failed: 'We could not start the email change. Please try again.',
      },
      password: {
        title: 'Password',
        lead: 'Changing your password signs you out of every other device.',
        newPasswordLabel: 'New password',
        newPasswordHint: 'At least 12 characters.',
        submit: 'Change password',
        submitting: 'Saving…',
        done: 'Your password was changed. Other devices were signed out.',
        failed: 'We could not change your password. Please try again.',
      },
      sessions: {
        title: 'Active devices',
        lead: 'These devices are signed in to your account. End any you do not recognize.',
        empty: 'No active devices.',
        thisDevice: 'This device',
        lastSeen: (when: string) => `Last active ${when}`,
        end: 'End session',
        endLabel: (device: string) => `End session on ${device}`,
        logoutAll: 'Log out everywhere',
        logoutAllHint: 'Ends every session, including this one.',
        working: 'Please wait…',
        failed: 'We could not update your sessions. Please try again.',
      },
      export: {
        title: 'Download your data',
        lead: 'Get a JSON file with your account, profile, reviews and their versions, helpful votes, library, notifications, and signed-in devices.',
        download: 'Download my data',
      },
      delete: {
        title: 'Delete account',
        lead: 'Deleting your account signs you out everywhere and disables it right away.',
        erase:
          'After 30 days your account is permanently erased, along with your reviews, votes, reports, and library. This cannot be undone.',
        passwordLabel: 'Type your password to confirm',
        submit: 'Delete my account',
        submitting: 'Deleting…',
        failed: 'We could not delete your account. Please try again.',
      },
    },
    confirmEmail: {
      successTitle: 'Email address changed',
      successBody: 'Your new email address is confirmed. Use it the next time you log in.',
      failedTitle: 'This link cannot be used',
      failedBody: 'The email change link is missing, has expired, or was already used.',
      failedHelp: 'Log in and start the change again from your security settings.',
      continue: 'Continue to RePrint',
      logIn: 'Log in',
    },
  },
  admin: {
    title: 'Administration',
    navLabel: 'Administration sections',
    navToggle: 'Admin menu',
    scrollableTable: (name: string) => `${name}, scrollable table`,
    reviewsNav: 'Review queue',
    dashboardNav: 'Dashboard',
    reportsNav: 'Reports queue',
    usersNav: 'Users',
    auditNav: 'Audit log',
    catalogNav: 'Catalog',
    mergeNav: 'Merge queue',
    genresNav: 'Genres and rules',
    featuredNav: 'Featured content',
    systemNav: 'System',
    system: {
      title: 'System',
      loadFailed: 'We could not load the system numbers. Please try again in a moment.',
      refreshNote: 'These numbers refresh every 30 seconds.',
      updatedAt: (time: string) => `Updated at ${time} UTC`,
      sourceHeading: 'Source requests',
      requestsPerSecond: 'Requests per second (last minute)',
      limit: (limit: number) => `Limit: ${limit} per second`,
      breaker: 'Circuit breaker',
      breakerOpen: 'Open: Source calls are paused',
      breakerClosed: 'Closed',
      cacheHeading: 'Search cache',
      hitRate: 'Hit rate',
      noLookups: 'No lookups yet',
      lookups: (hits: number, misses: number) => `${hits} hits, ${misses} misses`,
      queueHeading: 'Job queue',
      waiting: 'Waiting',
      active: 'Active',
      delayed: 'Delayed',
      failed: 'Failed',
      oldestWaiting: 'Oldest waiting job',
      nothingWaiting: 'Nothing is waiting',
      seconds: (n: number) => `${n} s`,
      minutes: (n: number) => `${n} min`,
    },
    catalog: {
      title: 'Catalog',
      loadFailed: 'We could not load the Catalog. Please try again in a moment.',
      totalsLabel: 'Catalog size',
      books: 'Books',
      editions: 'Editions',
      authors: 'Authors',
      growthHeading: 'Monthly growth',
      growthCaption: 'Books, Editions, and Authors added in each of the last 12 months (UTC)',
      month: 'Month',
      noGrowth: 'Nothing was added in the last 12 months.',
      mergeLink: 'Open the merge queue',
      genresLink: 'Manage Genres and rules',
    },
    merge: {
      title: 'Merge queue',
      loadFailed: 'We could not load the merge queue. Please try again in a moment.',
      listLabel: 'Possible duplicate Books',
      empty: 'No possible duplicates are waiting.',
      next: 'Show more',
      pairLabel: (a: string, b: string) => `${a} and ${b}`,
      reasonLabel: 'Why they match',
      authorsLabel: 'Authors',
      noAuthors: 'No Authors',
      counts: (editions: number, reviews: number, shelfEntries: number) =>
        `${editions} ${editions === 1 ? 'Edition' : 'Editions'} · ${reviews} ${reviews === 1 ? 'review' : 'reviews'} · ${shelfEntries} Shelf ${shelfEntries === 1 ? 'entry' : 'entries'}`,
      edit: (title: string) => `Edit ${title}`,
      keep: (title: string) => `Keep ${title}`,
      confirmHeading: (from: string, into: string) => `Merge ${from} into ${into}?`,
      confirmHint:
        'Reviews, Shelf entries, Editions, and Contributions move to the Book you keep. The other Book is removed and its page redirects. This cannot be undone.',
      confirm: 'Merge Books',
      merging: 'Merging…',
      cancel: 'Cancel',
      dismiss: 'Not a duplicate',
      dismissing: 'Dismissing…',
      merged: (reviews: number, shelfEntries: number, editions: number) =>
        `The Books were merged. Moved ${reviews} ${reviews === 1 ? 'review' : 'reviews'}, ${shelfEntries} Shelf ${shelfEntries === 1 ? 'entry' : 'entries'}, and ${editions} ${editions === 1 ? 'Edition' : 'Editions'}.`,
      dismissed: 'The pair was dismissed.',
      failed: 'We could not do that. Please try again.',
    },
    featured: {
      title: 'Featured content',
      loadFailed: 'We could not load featured content. Please try again in a moment.',
      genresHeading: 'Featured Genres',
      genresHint: (max: number) =>
        `Choose up to ${max} Genres for the Discover page, in the order they should appear.`,
      genresReadOnly: 'Only Admins can change the featured Genres.',
      genresLabel: 'Featured Genres',
      noGenres: 'No Genres are featured.',
      up: 'Up',
      down: 'Down',
      removeShort: 'Remove',
      featureShort: 'Feature',
      moveUp: (name: string) => `Move ${name} up`,
      moveDown: (name: string) => `Move ${name} down`,
      remove: (name: string) => `Remove ${name}`,
      addLabel: 'Add a Genre',
      addPlaceholder: 'Choose a Genre',
      add: 'Add Genre',
      full: (max: number) => `You can feature up to ${max} Genres.`,
      saveGenres: 'Save featured Genres',
      saving: 'Saving…',
      genresSaved: 'The featured Genres were saved.',
      reviewHeading: 'Featured review',
      reviewHint: 'Only an Approved review can be featured. It is shown on Discover with its Book.',
      noReview: 'No review is featured.',
      clear: 'Clear featured review',
      clearing: 'Clearing…',
      candidatesHeading: 'Approved reviews to choose from',
      candidatesLabel: 'Approved reviews',
      noCandidates: 'There are no Approved reviews to choose from yet.',
      byline: (rating: number, author: string, book: string) =>
        `${rating} of 5 by ${author} on ${book}`,
      feature: (book: string) => `Feature the review of ${book}`,
      featuring: 'Featuring…',
      current: 'Featured now',
      reviewSaved: 'The featured review was saved.',
      reviewCleared: 'The featured review was cleared.',
      failed: 'We could not save that. Please try again.',
    },
    genres: {
      title: 'Genres and rules',
      loadFailed: 'We could not load Genres and rules. Please try again in a moment.',
      genresHeading: 'Genres',
      listLabel: 'Genres',
      empty: 'There are no Genres yet.',
      counts: (books: number, rules: number) =>
        `${books} ${books === 1 ? 'Book' : 'Books'} · ${rules} ${rules === 1 ? 'rule' : 'rules'}`,
      archivedBadge: 'Archived',
      topLevel: 'Top level',
      parentLabel: 'Parent Genre',
      nameLabel: 'Name',
      slugLabel: 'Slug',
      slugHint: 'Lowercase letters, digits, and single hyphens.',
      descriptionLabel: 'Description',
      addHeading: 'Add a Genre',
      add: 'Add Genre',
      adding: 'Adding…',
      added: 'The Genre was added.',
      edit: (name: string) => `Edit ${name}`,
      save: 'Save Genre',
      saving: 'Saving…',
      saved: 'The Genre was saved.',
      cancel: 'Cancel',
      archive: (name: string) => `Archive ${name}`,
      restore: (name: string) => `Restore ${name}`,
      archived: 'The Genre was archived.',
      restored: 'The Genre was restored.',
      rulesHeading: 'Subject rules',
      rulesHint:
        'A rule maps Subjects that contain the pattern to a Genre. Changes apply when a Book is next ingested or refreshed.',
      rulesLabel: 'Subject rules',
      noRules: 'There are no Subject rules yet.',
      patternLabel: 'Pattern',
      ruleGenreLabel: 'Genre',
      priorityLabel: 'Priority (0 to 1000)',
      addRule: 'Add rule',
      addingRule: 'Adding…',
      ruleAdded: 'The rule was added.',
      removeRule: (pattern: string) => `Remove rule ${pattern}`,
      ruleRemoved: 'The rule was removed.',
      priority: (n: number) => `Priority ${n}`,
      failed: 'We could not save that. Please try again.',
    },
    book: {
      title: 'Edit Book',
      loadFailed: 'We could not load this Book. Please try again in a moment.',
      back: 'View the Book page',
      fieldsHeading: 'Details',
      titleLabel: 'Title',
      descriptionLabel: 'Description',
      genresLegend: 'Genres',
      seriesHeading: 'Series',
      seriesNameLabel: 'Series name',
      seriesPositionLabel: 'Position (may be decimal or empty)',
      addSeries: 'Add a Series',
      removeSeries: (name: string) => `Remove Series ${name || '(new)'}`,
      contributionsHeading: 'Contributions',
      authorNameLabel: 'Author name',
      roleLabel: 'Role',
      roles: {
        author: 'Author',
        co_author: 'Co-author',
        translator: 'Translator',
        illustrator: 'Illustrator',
        editor: 'Editor',
        narrator: 'Narrator',
        other: 'Other',
      },
      addContribution: 'Add a contribution',
      removeContribution: (name: string) => `Remove contribution ${name || '(new)'}`,
      newAuthorHint: 'A name that is not in the list creates a new Author.',
      primaryEditionLabel: 'Primary Edition',
      automaticEdition: 'Chosen automatically',
      editionOption: (parts: string[]) => parts.join(' · '),
      save: 'Save changes',
      saving: 'Saving…',
      saved: 'The Book was saved. Edited fields are now locked.',
      nothingChanged: 'Change a field first.',
      lockedHeading: 'Locked fields',
      lockedHint: 'A refresh never overwrites these.',
      noLocks: 'No fields are locked.',
      lockedBadge: 'Locked',
      originLine: (source: string, date: string) => `Set by ${source} on ${date}`,
      fieldNames: {
        title: 'Title',
        description: 'Description',
        genres: 'Genres',
        series: 'Series',
        contributions: 'Contributions',
        primaryEdition: 'Primary Edition',
        cover: 'Cover',
      } as Record<string, string>,
      coverHeading: 'Cover',
      coverAlt: (title: string) => `Cover of ${title}`,
      noCover: 'This Book has no Cover.',
      coverFileLabel: 'Upload a Cover image',
      coverHint: 'JPEG, PNG, or WebP up to 5 MB. It is stored at up to 600 px wide and locked.',
      coverUpload: 'Upload Cover',
      coverUploading: 'Uploading…',
      coverUploaded: 'The Cover was uploaded and locked.',
      coverChoose: 'Choose an image first.',
      refreshHeading: 'Refresh from the Source',
      refreshHint: 'Fetches the Source again. Locked fields stay as they are.',
      refresh: 'Refresh now',
      refreshing: 'Queuing…',
      refreshQueued: 'A refresh was queued. It can take a moment to show.',
      failed: 'We could not save that. Please try again.',
    },
    audit: {
      title: 'Audit log',
      loadFailed: 'We could not load the audit log. Please try again in a moment.',
      actorLabel: 'Actor (username)',
      actionLabel: 'Action',
      targetTypeLabel: 'Target type',
      targetIdLabel: 'Target ID',
      fromLabel: 'From',
      toLabel: 'To',
      any: 'Any',
      filter: 'Filter',
      clear: 'Clear filters',
      export: 'Export CSV',
      listLabel: 'Audit log',
      empty: 'No audit entries match these filters.',
      next: 'Show more',
      columns: {
        time: 'Time',
        actor: 'Actor',
        action: 'Action',
        target: 'Target',
        ip: 'IP',
        changes: 'Before and after',
      },
      noActor: 'Account erased',
      noIp: 'Not recorded',
      before: 'Before',
      after: 'After',
      noValues: 'No values recorded',
    },
    dashboard: {
      title: 'Moderation dashboard',
      loadFailed: 'We could not load the moderation dashboard. Please try again in a moment.',
      pendingLabel: 'Pending reviews',
      oldest: (age: string) => `Oldest has waited ${age}`,
      nothingWaiting: 'No reviews are waiting.',
      openQueue: 'Open the review queue',
      reportsLabel: 'Open reports',
      nothingReported: 'No reports are open.',
      openReports: 'Open the reports queue',
    },
    reviews: {
      title: 'Review queue',
      listLabel: 'Pending reviews',
      empty: 'No reviews are waiting for a decision.',
      loadFailed: 'We could not load the review queue. Please try again in a moment.',
      next: 'Show more',
      open: (title: string) => `Open the review of ${title}`,
      age: (text: string) => `Waiting ${text}`,
      ageMinutes: (n: number) => `${n} ${n === 1 ? 'minute' : 'minutes'}`,
      ageHours: (n: number) => `${n} ${n === 1 ? 'hour' : 'hours'}`,
      ageDays: (n: number) => `${n} ${n === 1 ? 'day' : 'days'}`,
      selectPrompt: 'Choose a review from the list to open it. Opening a review claims it for you.',
      notInQueue: 'That review is no longer waiting for a decision.',
      claimedByYou: (time: string) => `Claimed by you until ${time}.`,
      claimedByOther: (name: string) => `${name} is handling this review.`,
      claimFailed: 'We could not claim this review. Another Moderator may be handling it.',
      bookLabel: 'Book',
      reviewerLabel: 'Reviewer',
      ratingLabel: 'Rating',
      ratingOf: (n: number) => `${n} out of 5 stars`,
      editionNote: 'This review names a specific Edition.',
      spoilerFlag: 'Marked as containing spoilers',
      noSpoilerFlag: 'Not marked as containing spoilers',
      editedNote: (version: number) => `Edited review (version ${version})`,
      historyHeading: 'Reviewer history',
      approved: (n: number) => `${n} approved`,
      rejected: (n: number) => `${n} rejected`,
      reported: (n: number) => `${n} reported`,
      bodyHeading: 'Full text',
      untitled: 'No headline',
      detailLabel: 'Selected review',
      actionsLabel: 'Decision',
      approve: 'Approve',
      approving: 'Approving…',
      reject: 'Reject',
      rejecting: 'Rejecting…',
      rejectConfirm: 'Reject review',
      cancel: 'Cancel',
      reasonLabel: 'Reason (optional, shown to the author)',
      reasonHint: (max: number) => `Up to ${max} characters.`,
      phraseLabel: 'Saved phrase',
      phrasePlaceholder: 'Choose a saved phrase',
      phrases: [
        'This review does not follow the Community Guidelines.',
        'Please keep the review about the book, not about other people.',
        'This review contains spoilers that are not marked. Please mark them and resubmit.',
        'This review reads as an advertisement or spam.',
        'This review needs more detail about the book itself.',
      ],
      readOnly: 'Another Moderator holds this review, so decisions are turned off.',
      decided: (status: 'approved' | 'rejected') =>
        status === 'approved' ? 'The review was approved.' : 'The review was rejected.',
      decideFailed: 'We could not save that decision. Please try again.',
      shortcutsHeading: 'Keyboard shortcuts',
      shortcuts: 'A approves, R rejects, J is the next review, K is the previous one.',
      compareHeading: 'Changes since the last approved version',
      lastApprovedHeading: 'Last approved version',
      submittedHeading: 'Submitted for review',
      changed: 'Changed',
      unchanged: 'Unchanged',
      headlineLabel: 'Headline',
      spoilersLabel: 'Spoilers',
      spoilersYes: 'Marked',
      spoilersNo: 'Not marked',
    },
    reports: {
      title: 'Reports queue',
      listLabel: 'Reported reviews',
      empty: 'No reviews have open reports.',
      loadFailed: 'We could not load the reports queue. Please try again in a moment.',
      next: 'Show more',
      reviewBy: (name: string) => `Review by ${name}`,
      bookLabel: 'Book',
      hidden: 'Hidden until a moderator decides',
      reportCount: (n: number) => `${n} open ${n === 1 ? 'report' : 'reports'}`,
      oldest: (age: string) => `Oldest reported ${age} ago`,
      reportsHeading: 'Reports',
      reportedBy: (name: string) => `Reported by ${name}`,
      reasons: {
        unmarked_spoiler: 'Unmarked spoiler',
        offensive: 'Offensive or hateful',
        spam: 'Spam or advertising',
        off_topic: 'Off-topic',
        other: 'Other',
      },
      ratingOf: (n: number) => `${n} out of 5 stars`,
      spoilerFlag: 'Marked as containing spoilers',
      untitled: 'No headline',
      actionsLabel: 'Decision',
      dismiss: 'Dismiss',
      dismissing: 'Dismissing…',
      dismissed: 'The reports were dismissed.',
      unpublish: 'Unpublish',
      unpublishing: 'Unpublishing…',
      unpublishConfirm: 'Unpublish review',
      unpublished: 'The review was unpublished.',
      reasonLabel: 'Reason (required, shown to the author)',
      reasonHint: (max: number) => `Up to ${max} characters.`,
      reasonRequired: 'Give a reason.',
      suspendAuthor: 'Suspend author',
      suspendConfirm: 'Suspend author',
      suspending: 'Suspending…',
      suspended: 'The author was suspended.',
      suspendReasonLabel: 'Suspension reason (required, shown to the author)',
      suspendUntilLabel: 'Suspended until (optional, UTC)',
      suspendUntilHint: 'Leave empty to suspend until an Admin lifts it.',
      cancel: 'Cancel',
      actionFailed: 'We could not save that action. Please try again.',
    },
    users: {
      title: 'Users',
      loadFailed: 'We could not load users. Please try again in a moment.',
      searchLabel: 'Search by username or email',
      searchLabelLimited: 'Search by username',
      roleLabel: 'Role',
      statusLabel: 'Status',
      joinedFromLabel: 'Joined from',
      joinedToLabel: 'Joined to',
      any: 'Any',
      filter: 'Filter',
      clear: 'Clear filters',
      listLabel: 'Users',
      empty: 'No users match these filters.',
      next: 'Show more',
      columns: {
        user: 'User',
        email: 'Email',
        status: 'Status',
        roles: 'Roles',
        joined: 'Joined',
        reviews: 'Reviews',
        reports: 'Reports received',
      },
      roles: { member: 'Member', moderator: 'Moderator', admin: 'Admin' },
      statuses: {
        active: 'Active',
        unverified: 'Unverified',
        suspended: 'Suspended',
        deleted: 'Deleted',
      },
      back: 'Back to users',
      noEmail: 'Hidden in the limited view',
      detail: {
        profile: 'Profile',
        email: 'Email',
        verified: (date: string) => `Verified ${date}`,
        notVerified: 'Not verified',
        bio: 'Bio',
        noBio: 'No bio',
        joined: 'Joined',
        suspendedUntil: (date: string) => `Suspended until ${date}`,
        suspendedIndefinitely: 'Suspended until an Admin lifts it',
        suspendedReason: 'Reason',
        deletedAt: (date: string) => `Deleted ${date}`,
        reviewsHeading: 'Reviews by status',
        reviewStatuses: {
          pending: 'Pending',
          approved: 'Approved',
          rejected: 'Rejected',
          unpublished: 'Unpublished',
        },
        reportsHeading: 'Reports',
        reportsFiled: 'Filed',
        reportsReceived: 'Received',
        sessionsHeading: 'Sessions',
        noSessions: 'No active sessions.',
        sessionMeta: (ip: string | null, seen: string) =>
          `${ip ?? 'IP not recorded'} · last seen ${seen}`,
        auditHeading: 'Audit history',
        noAudit: 'No audit entries.',
        auditBy: (name: string | null) => (name ? `by ${name}` : 'by the system'),
        limitedNote: 'Sessions and audit history are not part of your view.',
        profileLink: 'Public profile',
      },
      actions: {
        heading: 'Actions',
        rolesHeading: 'Roles',
        grant: (role: string) => `Make ${role}`,
        revoke: (role: string) => `Remove ${role} role`,
        granted: 'The role was granted.',
        revoked: 'The role was removed.',
        unchanged: 'Nothing changed; the user was already in that state.',
        suspend: 'Suspend',
        suspendConfirm: 'Suspend user',
        suspending: 'Suspending…',
        suspendedDone: 'The user was suspended.',
        reasonLabel: 'Suspension reason (required, shown to the user)',
        reasonHint: (max: number) => `Up to ${max} characters.`,
        untilLabel: 'Suspended until (optional, UTC)',
        untilHint: 'Leave empty to suspend until an Admin lifts it.',
        cancel: 'Cancel',
        unsuspend: 'Unsuspend',
        unsuspendedDone: 'The suspension was lifted.',
        revokeSessions: 'End all sessions',
        revokedDone: (n: number) => `${n} ${n === 1 ? 'session was' : 'sessions were'} ended.`,
        resend: 'Resend verification email',
        resendDone: 'The verification email was sent.',
        resendNotSent: 'The email is already verified, so nothing was sent.',
        working: 'Working…',
        failed: 'We could not save that action. Please try again.',
      },
    },
  },
  error: {
    title: 'Something went wrong',
    notFoundTitle: 'Page not found',
    forbiddenTitle: 'Not allowed',
    forbiddenBody: 'You do not have permission to see this page.',
    body: 'We could not load this page. Please try again in a moment.',
    notFoundBody: 'The page you are looking for does not exist.',
    home: 'Back to home',
  },
  legal: {
    // The owner's monitored inbox (M8-T17).
    contactEmail: 'psmak4@gmail.com',
    terms: {
      title: 'Terms of Service',
      description: 'The rules for using RePrint: accounts, reviews, and acceptable use.',
      sections: [
        {
          heading: 'Using RePrint',
          paragraphs: [
            'RePrint is a place to discover books and read and write reviews. By creating an account or using the site you agree to these terms.',
            'You must give a real email address, keep your password private, and tell us if you think someone else has used your account.',
          ],
        },
        {
          heading: 'Your reviews',
          paragraphs: [
            'You keep ownership of what you write. By submitting a review you give RePrint a licence to show it on the site and in search results.',
            'Every review is read by a moderator before it is published. We may reject a review that breaks the Community Guidelines, and we may unpublish an approved review that does.',
            'You may write one review per Book. Editing a published review sends it back for approval.',
          ],
        },
        {
          heading: 'Acceptable use',
          paragraphs: [
            'Do not use RePrint to harass others, post spam, scrape the site at a rate that harms it, or try to get around its security.',
            'We may suspend an account that breaks these terms.',
          ],
        },
        {
          heading: 'Changes and deletion',
          paragraphs: [
            'You can delete your account at any time from Settings. We may update these terms and will say so on this page.',
          ],
        },
      ],
    },
    privacy: {
      title: 'Privacy Policy',
      description:
        'What RePrint collects, how long it is kept, and your rights under GDPR and CCPA.',
      sections: [
        {
          heading: 'What we collect',
          paragraphs: [
            'Your email address, username, display name, password (stored only as a hash), profile details you choose to add, your reviews, ratings, Helpful votes, reports, and your Library.',
            'We also keep the IP address of each session and of each action taken by a moderator or admin.',
          ],
        },
        {
          heading: 'How long we keep it',
          paragraphs: [
            'IP addresses in sessions and the audit log are cleared after 90 days.',
            'When you delete your account it is disabled at once and permanently erased after 30 days, along with your reviews, votes, reports, and Library.',
          ],
        },
        {
          heading: 'Cookies and analytics',
          paragraphs: [
            'RePrint uses one session cookie to keep you logged in. Our analytics is cookieless: it sets no cookies and does not track you across sites, so there is no cookie banner.',
          ],
        },
        {
          heading: 'Your rights under GDPR and CCPA',
          paragraphs: [
            'If you live in the European Economic Area, the United Kingdom, or California, you have the right to access your data, correct it, delete it, receive a portable copy, object to or restrict how it is used, and to not be discriminated against for using these rights. We do not sell personal information.',
            'You can download a JSON export of your data and delete your account from Settings. For anything else, write to us using the Contact page.',
          ],
        },
        {
          heading: 'Who else sees your data',
          paragraphs: [
            'We use service providers to host the site, send email, and report errors. They handle data only on our behalf. Book data and covers come from Open Library; we do not send them your personal information.',
          ],
        },
      ],
    },
    guidelines: {
      title: 'Community Guidelines',
      description: 'What gets a review rejected, so you can write reviews that are approved.',
      sections: [
        {
          heading: 'Why we moderate',
          paragraphs: [
            'Every review is read by a moderator before it is published, so readers can trust what they see. A rejected review stays visible only to you, with the reason if the moderator gave one. You can edit it and send it again.',
          ],
        },
        {
          heading: 'A review may be rejected for',
          items: [
            'An unmarked spoiler. Tick “Contains spoilers” if your review gives away the plot.',
            'Offensive or hateful content, including attacks on people for who they are.',
            'Spam or advertising, including links and promotion of your own products or services.',
            'Being off-topic: the review is not about the Book.',
            'Other reasons the moderator explains in a note.',
          ],
        },
        {
          heading: 'Writing a good review',
          paragraphs: [
            'Say what you thought and why. Reviews are plain text between 50 and 10,000 characters; links are shown as text and are not clickable. You can review each Book once.',
          ],
        },
        {
          heading: 'Reporting a review',
          paragraphs: [
            'If a published review breaks these guidelines, use Report on the review. A moderator will look at it and may unpublish it.',
          ],
        },
      ],
    },
    about: {
      title: 'About RePrint',
      description:
        'RePrint is a place to discover books and read reviews you can trust, each approved by a moderator.',
      sections: [
        {
          heading: 'Discovery and trust first',
          paragraphs: [
            'RePrint helps you find your next book and read reviews you can trust. Every review is approved by a moderator before it is published, every reviewer has a verified account, and each Member can review a Book once.',
            'Your Library, with Shelves for Want to read, Reading, and Read, gives you a place to keep track of what you want to read and what you have finished.',
          ],
        },
        {
          heading: 'Where the data comes from',
          paragraphs: [
            'Book information and covers come from Open Library and are kept in RePrint’s own Catalog. Reviews, ratings, and Libraries belong to RePrint and its Members.',
          ],
        },
      ],
    },
    contact: {
      title: 'Contact',
      description: 'How to reach the RePrint team about your account, a review, or privacy.',
      sections: [
        {
          heading: 'Get in touch',
          paragraphs: [
            'For questions about your account, a rejected or unpublished review, a privacy request, or a mistake in the Catalog, write to us.',
          ],
        },
        {
          heading: 'Reporting a review',
          paragraphs: [
            'To report a published review, use Report on the review itself so a moderator sees it right away.',
          ],
        },
      ],
      emailLabel: 'Email',
    },
  },
} as const
