export const copy = {
  shell: {
    brand: 'RePrint',
    skipToContent: 'Skip to main content',
    homeLinkLabel: 'RePrint home',
    searchLabel: 'Search',
    search: {
      inputLabel: 'Search books and authors',
      placeholder: 'Search books and authors',
      submit: 'Search',
      suggestionsLabel: 'Suggestions',
      bookKind: 'Book',
      authorKind: 'Author',
      resultCount: (count: number) =>
        count === 0
          ? 'No suggestions'
          : `${count} ${count === 1 ? 'suggestion' : 'suggestions'} available`,
    },
    accountLabel: 'Account',
    legalNavLabel: 'Legal and help',
    openLibraryCredit: 'Book data and covers courtesy of',
    openLibraryName: 'Open Library',
    openLibraryUrl: 'https://openlibrary.org',
    logIn: 'Log in',
    register: 'Register',
    logOut: 'Log out',
    accountMenuLabel: 'Account menu',
    notifications: {
      label: 'Notifications',
      unreadLabel: (count: number) => `Notifications, ${count} unread`,
      empty: 'No notifications yet.',
      unreadMark: 'Unread',
      messages: {
        review_approved: 'Your review was approved and is now published.',
        review_rejected: 'Your review was not approved.',
        review_unpublished: 'Your review was unpublished.',
        password_changed: 'Your password was changed.',
        email_changed: 'Your email address was changed.',
      },
      readFailed: 'We could not update your notifications.',
    },
    legalLinks: [
      { label: 'About', href: '/about' },
      { label: 'Terms of Service', href: '/terms' },
      { label: 'Privacy Policy', href: '/privacy' },
      { label: 'Community Guidelines', href: '/community-guidelines' },
      { label: 'Contact', href: '/contact' },
    ],
  },
  home: {
    title: 'Discover books. Read reviews you can trust.',
    lead: 'Every review on RePrint is approved by a moderator before anyone sees it.',
    cta: 'Browse books',
  },
  search: {
    title: (q: string) => (q ? `Search: ${q}` : 'Search'),
    heading: 'Search results',
    prompt: 'Type at least 2 characters to search for books and authors.',
    queryLabel: 'Search books and authors',
    tabsLabel: 'Result types',
    booksTab: 'Books',
    authorsTab: 'Authors',
    filtersLabel: 'Filters',
    language: 'Language',
    decade: 'First published',
    minRating: 'Minimum rating',
    sort: 'Sort by',
    anyOption: 'Any',
    decadeOption: (year: number) => `${year}s`,
    minRatingOption: (stars: number) => `${stars} stars and up`,
    genreActive: (slug: string) => `Genre: ${slug}`,
    genreRemove: 'Remove genre filter',
    catalogOnly: 'Genre, language, and rating filters show only books already on RePrint.',
    sorts: {
      relevance: 'Relevance',
      most_reviewed: 'Most reviewed',
      highest_rated: 'Highest rated',
      newest: 'Newest',
    },
    apply: 'Apply filters',
    clear: 'Clear filters',
    resultCount: (count: number) => `${count} ${count === 1 ? 'result' : 'results'} on this page`,
    empty: 'No results found. Try a different spelling or fewer filters.',
    sourceUnavailable:
      "We couldn't reach our wider book search just now, so these are only books already on RePrint.",
    loadFailed: "We couldn't load search results. Please try again in a moment.",
    pagesLabel: 'Pages',
    previous: 'Previous',
    next: 'Next',
    pageOf: (page: number) => `Page ${page}`,
  },
  books: {
    coverAlt: (title: string) => `Cover of ${title}`,
    byAuthors: (names: string) => `by ${names}`,
    firstPublished: (year: number) => `First published ${year}`,
    noReviews: 'No RePrint reviews yet',
    ratingLabel: (average: string, count: number) =>
      `Rated ${average} out of 5 from ${count} ${count === 1 ? 'review' : 'reviews'}`,
    reviewCount: (count: number) => `(${count})`,
  },
  auth: {
    emailLabel: 'Email',
    usernameLabel: 'Username',
    passwordLabel: 'Password',
    inviteCodeLabel: 'Invite code',
    inviteCodeRequired: 'Enter your invite code.',
    inviteCodeHint: 'RePrint is invite-only for now. Enter the code you were given.',
    submitting: 'Please wait…',
    genericError: 'Something went wrong. Please try again.',
    login: {
      title: 'Log in',
      submit: 'Log in',
      noAccount: 'New to RePrint?',
      registerLink: 'Create an account',
      forgotLink: 'Forgot your password?',
    },
    register: {
      title: 'Create your account',
      submit: 'Create account',
      haveAccount: 'Already have an account?',
      loginLink: 'Log in',
      passwordHint: 'At least 12 characters.',
      usernameHint: '3 to 30 letters, numbers, or underscores.',
      checkEmailTitle: 'Check your email',
      checkEmailBody:
        'If the address can be used, we sent a link to confirm it. The link works for 24 hours.',
    },
    forgot: {
      title: 'Reset your password',
      lead: 'Enter your email and we will send a link to choose a new password.',
      submit: 'Send reset link',
      backToLogin: 'Back to log in',
      checkEmailTitle: 'Check your email',
      checkEmailBody:
        'If that address has an account, we sent a link to reset the password. The link works for 1 hour.',
    },
    reset: {
      title: 'Choose a new password',
      submit: 'Set new password',
      newPasswordLabel: 'New password',
      passwordHint: 'At least 12 characters.',
      doneTitle: 'Password updated',
      doneBody: 'Your password has been changed. Log in with it to continue.',
      logIn: 'Log in',
      invalidTitle: 'This link cannot be used',
      invalidBody: 'The reset link is missing, has expired, or was already used.',
      requestNew: 'Request a new link',
    },
    verify: {
      successTitle: 'Email confirmed',
      successBody: 'Thanks. Your email address is verified, so you can now write reviews.',
      failedTitle: 'This link cannot be used',
      failedBody: 'The verification link is missing, has expired, or was already used.',
      failedHelp: 'Log in and use the banner at the top of any page to send a new link.',
      continue: 'Continue to RePrint',
      logIn: 'Log in',
    },
    banner: {
      label: 'Email verification',
      message: 'Confirm your email address to write reviews, vote, and report.',
      resend: 'Resend link',
      sending: 'Sending…',
      sent: 'We sent a new link. It works for 24 hours.',
      failed: 'We could not send the link. Please try again.',
    },
  },
  settings: {
    title: 'Settings',
    navLabel: 'Settings sections',
    profileTab: 'Profile',
    securityTab: 'Security',
    profile: {
      title: 'Profile',
      lead: 'This is what other Members see on your profile.',
      displayNameLabel: 'Display name',
      bioLabel: 'Bio',
      bioCounter: (used: number, max: number) => `${used} of ${max} characters`,
      libraryPublicLabel: 'Show my library on my profile',
      libraryPublicHint: 'When this is off, only you can see which Books are on your Shelves.',
      emailDecisionsLabel: 'Email me when a moderator decides on my review',
      emailDecisionsHint: 'Security emails about your account are always sent.',
      save: 'Save changes',
      saving: 'Saving…',
      saved: 'Your profile was saved.',
      failed: 'We could not save your profile. Please try again.',
    },
    avatar: {
      title: 'Avatar',
      currentAlt: 'Your current avatar',
      previewAlt: 'Preview of your new avatar',
      fileLabel: 'Choose an image',
      fileHint: 'JPEG, PNG, WebP, or GIF up to 5 MB. It is cropped to a square.',
      upload: 'Upload avatar',
      uploading: 'Uploading…',
      uploaded: 'Your avatar was updated.',
      chooseFile: 'Choose an image to upload.',
      failed: 'We could not upload the image. Please try again.',
    },
    security: {
      title: 'Security',
      currentPasswordLabel: 'Current password',
      email: {
        title: 'Email address',
        lead: (email: string) =>
          `Your email is ${email}. A new address takes effect once you confirm it.`,
        newEmailLabel: 'New email address',
        submit: 'Change email',
        submitting: 'Sending…',
        pendingTitle: 'Check your new inbox',
        pendingBody: (email: string) =>
          `We sent a link to ${email}. Your email stays the same until you open it. The link works for 24 hours.`,
        failed: 'We could not start the email change. Please try again.',
      },
      password: {
        title: 'Password',
        lead: 'Changing your password signs you out of every other device.',
        newPasswordLabel: 'New password',
        newPasswordHint: 'At least 12 characters.',
        submit: 'Change password',
        submitting: 'Saving…',
        done: 'Your password was changed. Other devices were signed out.',
        failed: 'We could not change your password. Please try again.',
      },
      sessions: {
        title: 'Active devices',
        lead: 'These devices are signed in to your account. End any you do not recognize.',
        empty: 'No active devices.',
        thisDevice: 'This device',
        lastSeen: (when: string) => `Last active ${when}`,
        end: 'End session',
        endLabel: (device: string) => `End session on ${device}`,
        logoutAll: 'Log out everywhere',
        logoutAllHint: 'Ends every session, including this one.',
        working: 'Please wait…',
        failed: 'We could not update your sessions. Please try again.',
      },
      delete: {
        title: 'Delete account',
        lead: 'Deleting your account signs you out everywhere and disables it right away.',
        erase:
          'After 30 days your account is permanently erased, along with your reviews, votes, reports, and library. This cannot be undone.',
        passwordLabel: 'Type your password to confirm',
        submit: 'Delete my account',
        submitting: 'Deleting…',
        failed: 'We could not delete your account. Please try again.',
      },
    },
    confirmEmail: {
      successTitle: 'Email address changed',
      successBody: 'Your new email address is confirmed. Use it the next time you log in.',
      failedTitle: 'This link cannot be used',
      failedBody: 'The email change link is missing, has expired, or was already used.',
      failedHelp: 'Log in and start the change again from your security settings.',
      continue: 'Continue to RePrint',
      logIn: 'Log in',
    },
  },
  error: {
    title: 'Something went wrong',
    notFoundTitle: 'Page not found',
    body: 'We could not load this page. Please try again in a moment.',
    notFoundBody: 'The page you are looking for does not exist.',
    home: 'Back to home',
  },
} as const
